sirixdb/sirix

README.md

The *Asynchronous, Temporal  REST With Vert.x, Keycloak and Kotlin Coroutines* link points to 404 page. Added correct reference

Fixed hackernoon link

---

bundles/sirix-rest-api/docker-compose.yml
docker_push.sh

Working on 
#50 Docker setup / Fix README
#51  Docker compose
#100 Starting a rest-api service that fails to connect to keycloak exits with status code 0
Some initial feedback would be great before proceeding further, as I have limited knowledge about the project.
1. Planning to add multi stage docker build, so that we can avoid doing mvn build before running docker
2. Added image name to the docker compose file itself, Avoid running docker commands directly.
3. Network configuration is unnecessary with docker compose. Containers are reachable to each other with the service name as hostname. Initially we could provide in the readme to change the hostname in sirix-conf.json file as:
```"keycloak.url": "http://keycloak:8080/auth/realms/master"```
Eventually I would suggest using environment …

[WIP] Docker and docker-compose issues

---

bundles/sirix-rest-api/Dockerfile
docker_push.sh

Closes #51 
Closes #100 
- Added docker multi stage build. No need to run ```mvn package``` command outside the container anymore.
- Updated the base images to use smaller disk size. Now the final build is around 370 MB
- Updated deprecated commands from Dockerfile
- The localhost url in conf file is automatically updated with the keycloack url upon building the container.
We Need to test the container thoroughly once and make sure it is working exactly as outside the container

Docker multistage build

---

bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/SirixVerticle.kt
bundles/sirix-rest-api/src/main/resources/sirix-conf.json

- Make OAuth flow configurable between PASSWORD and AUTH_CODE
- add new endpoint for getting the auth server url login page with redirect_uri set
- Change name of /login endpoint to /token 
- add relevant values in config file
I tested the auth_flow manually with my own web app. If there is a way to make an automated test based on this, let me know. I'm curious how to do that.  
Please send me your feedback on what you think

Make OAuth flow configurable between PASSWORD and AUTH_CODE

---

build.gradle

This PR is to provide support for maven central publication and maven artifact signing.
The generated jar will contain the required tags by maven central like **description, url, license etc. in the pom.xml**
Also during maven publication, the published jar will be signed, to give signing properties, the below properties can be added to a gradle.properties file under USER_HOME (create a new file if not present)
**gradle.properties**
signing.keyId=24875D73
signing.password=secret
signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg
**Note**
Either `gradlew release` (or) the following command can also be used to just publish jars to maven central 
`gradlew publishAllPublicationsToMavenRepository`

Gradle Support - Maven central publish support with signing

---

.travis.deploy.artifacts.sh
.travis.yml
Dockerfile
build.gradle

The following changes are done,
- Travis updates to support gradle
- DockerFile updates to support gradle
**Travis updates**
In travis, we now have 3 stages,
- 1 Test
- 2 Deploy (Sonatype and Docker)

Gradle support - Travis changes

---

bundles/sirix-rest-api/src/main/resources/sirix-conf.json
docker-compose.yml

I have updated the docker-compose to use keycloak startup-scripts. This way we can create any type of user with any type of user before start-up of keycloak server.
**Problems**
1. Docker compose V3 doesn't support depends_on condition. So sirix_server will fail until the keycloak is up and running.
**Soultion** 
Since `restart: always` is set, sirix_server will restart always until keycloak is up
2. sirix-config.json contains keycloak URL as localhost:8080 / localhost:3005. Keycloak ports is not bound to sirix container thus 8080 and 3005 will not be accessible. 
**Soultion**
Modified localhost to keycloak (service name). Such that keycload will be resolved to keycloak server IP.

Docker compose updates with create-keycloak startup script

---

bundles/sirix-core/src/main/java/org/sirix/service/json/serialize/JsonSerializer.java

Provided support for pretty printing of JSONSerializer. 
The following builder methods can be used to construct the JSON which will handle pretty printing in a common location (If required)
- appendObjectStart()
- appendObjectEnd()
- appendArrayStart()
- appendArrayEnd()
- appendObjectKey()
- appendObjectValue() 
- appendObjectKeyValue()
- appendObjectSeparator()
- quote()

JSON Serializer support for pretty printing #192

---

bundles/sirix-core/src/main/java/org/sirix/service/json/serialize/StringValue.java

Replace a switch with a HashMap and break out the specific unicode
escaping to a separate function. Fixes #16

Reduce cyclomatic complexity in service.json.serialize.StringValue.escape

---

bundles/sirix-core/src/main/java/org/sirix/node/SirixDeweyID.java

I did this by replacing the switch cases with a single line with a calculation and replacing the
if else statements in the beginning of the function with a for-loop containing two if statements.
I did this to make the code easier to read and understand.

Refactor/SirixDeweyID.setDivisionBitArray: Reduced the cyclomatic complexity from 29 to 8.

---

bundles/sirix-core/src/main/java/org/sirix/io/ram/RAMStorage.java
bundles/sirix-core/src/test/java/org/sirix/access/StorageTest.java

The underlying bool in `RAMStorage.exists()` is only set on construction, and not properly set to false when `.truncate()` is called. This patch sets the bool to false in `truncate` and then sets it to true whenever `write` and `writeUberPageReference` succeeds. The patch also adds tests for the bug.
The whitespace noise comes from `RAMStorage.java` having Windows CRLF line endings. I took the liberty to change this to Unix line endings to match the rest of the source tree.

tests: extend StorageTest and fix bug in RAMStorage.truncate

---

build.gradle

Added missing compiler flags, which were preventing the javadoc from being generated.

allow javadoc to compile

---

Dockerfile
build.gradle
gradle/wrapper/gradle-wrapper.properties

Ran ./gradlew wrapper --gradle-version 6.5.1 to upgrade the
reference to gradle. Upgraded the Dockerfile to use the correct
version of the Gradle as well.  I was able to build the jar
locally as well as a new Docker image without any issues.
In addition I added a check to verify that you running with the
proper version of Java. When I was first trying to get things
to compile gradle would fail with a cryptic message about plugins
because I was using a earlier version of Java. Hopefully this
will prevent that from happening in the future.

Upgrade to Gradle 6.5.1

---

bundles/sirix-core/src/main/resources/logback.xml

remove hard-coded USER_HOME in logback config, use ${user.home}

remove hard-coded USER_HOME, use ${user.home}

---

docker-compose.yml

I also removed the anonymous volume `/opt/sirix`, as I don't see the purpose in mounting the entire sirix directory in a volume (and in an anonymous volume in particular).

fix docker-compose to write data to a named volume

---

bundles/sirix-core/build.gradle
bundles/sirix-core/src/main/java/org/sirix/access/DatabaseManager.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabaseModule.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabaseType.java
bundles/sirix-core/src/main/java/org/sirix/access/Databases.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalDatabaseFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalJsonDatabaseFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalXmlDatabaseFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/json/JsonResourceStore.java
bundles/sirix-core/src/main/java/org/sirix/access/xml/XmlResourceStore.java
libraries.gradle

Adds Dagger as a dependency to the project. Dagger is used in sirix-core, to create a `DatabaseManager` component.  This component, in this initial stage will simple register dependencies to create `Database` instances. In order to achieve this, a new `LocalDatabaseFactory` concept was introduced, with implementations for Json and XML.
At this point, the component is hidden behind `Databases`, in order to avoid breaking the entrypoint.
The next stages in this track is to extract most of the `Databases` business logic (e.g., sessions map) into separate classes, in order to increase maintainability and testing.
Closes #343

Introduce Dagger as DI framework for the project

---

bundles/sirix-core/src/main/java/org/sirix/access/AbstractLocalDatabase.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabaseManager.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabaseModule.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabaseSessionPool.java
bundles/sirix-core/src/main/java/org/sirix/access/Databases.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabasesInternals.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalJsonDatabase.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalJsonDatabaseFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalXmlDatabase.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalXmlDatabaseFactory.java
bundles/sirix-core/src/test/java/org/sirix/access/DatabaseSessionPoolTest.java

This patch extracts the database session management into its own class. Also, it adds tests to the session management logic. This new class is maintained by Dagger.
Closes #382

Extract database session management to a separate class

---

bundles/sirix-core/src/main/java/org/sirix/access/Databases.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabasesInternals.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalDatabase.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalJsonDatabaseFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalXmlDatabaseFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/WriteLocksRegistry.java
bundles/sirix-core/src/main/java/org/sirix/access/json/JsonResourceStore.java
bundles/sirix-core/src/main/java/org/sirix/access/xml/XmlResourceStore.java
bundles/sirix-core/src/test/java/org/sirix/access/WriteLocksRegistryTest.java

This patch extracts write lock management on `ResourceManager` to its own class. This class is now being registered in the central `DatabaseManager` component.

Extract resource write lock management to its own class

---

bundles/sirix-core/src/main/java/org/sirix/access/AbstractResourceStore.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabaseManager.java
bundles/sirix-core/src/main/java/org/sirix/access/DatabaseModule.java
bundles/sirix-core/src/main/java/org/sirix/access/GenericLocalDatabaseComponent.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalDatabase.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalDatabaseModule.java
bundles/sirix-core/src/main/java/org/sirix/access/json/JsonLocalDatabaseComponent.java
bundles/sirix-core/src/main/java/org/sirix/access/json/JsonLocalDatabaseModule.java
bundles/sirix-core/src/main/java/org/sirix/access/json/JsonResourceStore.java
bundles/sirix-core/src/main/java/org/sirix/access/json/LocalJsonDatabaseFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/TransactionManagerImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/page/PageTrxFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/xml/LocalXmlDatabaseFactory.java
bundles/sirix-core/src/main/java/org/sirix/access/xml/XmlLocalDatabaseComponent.java
bundles/sirix-core/src/main/java/org/sirix/access/xml/XmlLocalDatabaseModule.java
bundles/sirix-core/src/main/java/org/sirix/access/xml/XmlResourceStore.java
bundles/sirix-core/src/main/java/org/sirix/dagger/DatabaseName.java
bundles/sirix-core/src/main/java/org/sirix/dagger/DatabaseScope.java

This patch declares a database lifecycle as a [Dagger sub-component](https://dagger.dev/dev-guide/subcomponents.html).
At this point, the system's main component, `DatabaseManager` provides a set of methods, `DatabaseManager#jsonDatabaseBuilder` and `DatabaseManager#xmlDatabaseBuilder`, which are responsible for creating a new sub-component (per call) that not only inherits all the instances from the parent component, but also manages a new container of instances that represent a `Database` instance.
These two new subcomponents `JsonLocalDatabaseComponent` and `XmlLocalDatabaseComponent` will each be responsible for managing a Json and Xml database session, respectfully. Having one subcomponent type per database type prevents Xml instances from being instantiated on a Json database, and …

Introduce database-level subcomponent

---

bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractNodeHashing.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractNodeReadOnlyTrx.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/InternalNodeReadOnlyTrx.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/InternalJsonNodeReadOnlyTrx.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/InternalJsonNodeTrx.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeHashing.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeReadOnlyTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonResourceManagerImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/xml/InternalXmlNodeReadOnlyTrx.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/xml/XmlNodeHashing.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/xml/XmlNodeReadOnlyTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/xml/XmlNodeTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/page/NodePageTrx.java
bundles/sirix-core/src/main/java/org/sirix/api/NodeTrx.java
bundles/sirix-core/src/main/java/org/sirix/api/PageTrx.java

Summary:
This commit pushes all the encoding agnonstic logic of read-only transactions to
AbstractNodeReadOnlyTrx.

Remove duplicate code between Json and Xml read only transaction

---

bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractResourceManager.java
bundles/sirix-core/src/main/java/org/sirix/api/ResourceManager.java
bundles/sirix-core/src/main/java/org/sirix/page/RevisionRootPage.java
bundles/sirix-core/src/main/java/org/sirix/page/UberPage.java
bundles/sirix-core/src/main/java/org/sirix/settings/VersioningType.java

Removes the redundant `org.sirix.page.UberPage#getRevision` and correspondent field. Also, pull some of the methods related to last committed revision up to the interface, as their default implementation is straightforward enough to live there.

Removes redudant revision field in UberPage

---

bundles/sirix-core/src/main/java/org/sirix/service/xml/shredder/WikipediaImport.java

This commit fixes a potential vulnerability detected by SonarCloud. SonarCloud recommends disabling DOCTYPE declerations when constructing the XMLInputFactory to resolve the problem

Fix XMLInputFactory vulnerability

---

bundles/sirix-core/src/main/java/org/sirix/io/filechannel/FileChannelReader.java

I noticed that it is possible to make working with ByteBuffer safer.
Imagine a situation where you read fewer bytes than expected, then simply calling `position(0)` and trying to retrieve the read data will probably result in getting incorrect data because that buffer's **limit** will still be the buffer **size.**
However, if you use `flip()`, the buffer **limit** is set to its current **position** (equal to the number of bytes read) and **position** to 0. So, an exception will occur if you try to get more bytes from the buffer than were read.

Make working with ByteBuffer more safe

---

bundles/sirix-core/src/main/java/org/sirix/access/trx/page/NodePageReadOnlyTrx.java

Hello!
I spotted unnecessary CompletableFuture allocation in the `getPreviousPageFragments` method. I think it is safe to get rid of it.

Fix unnecessary allocation of CompletableFuture

---

.github/workflows/gradle.yml

Uses actions/cache to cache Gradle dependencies to speed up CI runs. Also stops the Gradle daemon at the end of the job so the cache can be built in the post-workflow steps.
See https://github.com/actions/cache/blob/main/examples.md#java---gradle

ci: Cache gradle dependencies

---

docker-compose.yml

Added healthcheck to make sirix server wait until keycloak is completely up and running. Fixes sirixdb/sirix#549

Add healthcheck to verify if keycloak is up before running server.

---

README.md

Updated the instructions for starting Keycloak and server with `docker compose`. 
Key Changes:
1. Shifted the instructions for running the Keycloak without docker compose up
2. Shifted the instructions for running Keycloak with docker compose below.
3. Edited the instructions for running Keycloak and Sirix server with docker compose.
4. Updated the instructions to change the `keycloak.url` field for the configuration files to http://host.docker.internal:8080/auth/realms/sirixdb instead of http://localhost:8080/auth/realms/sirixdb or http://sirix_keycloak_1:8080/auth/realms/sirixdb

Update instructions for running server with docker compose

---

bundles/sirix-core/src/main/java/org/sirix/io/iouring/IOUringStorage.java
libraries.gradle

I suggest using this jasyncfio configuration for now.
In this configuration, using io_uring the testChicago on my machine is consistently slightly (about 20 sec) faster than the other I/O backend.
To further optimize, I would go in the direction of reducing allocation per operation, namely to implement reading via io_uring ring buffer feature.
Also, updated jasyncfio to the latest version.

Change io_uring configuration

---

bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/AbstractCreateHandler.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/Handler.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/json/JsonCreate.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/xml/XmlCreate.kt

Refactored common logics to `AbstractCreateHandler.kt`. 
Refactored following common functions to abstract class:
- `handle`
- `createOrRemoveAndCreateResource`
- `shredder`
- `createMultipleResources`
Renamed `insert[Json/Xml]SubtreeAsFirstChild` to `insertResourceSubtreeAsFirstChild` for abstracting in the common function.

Refactor to extract common logic between XML and JSON creation

---

README.md

I have started using Sirix both as a developer and a user. As a best practice, I prefer to locate the documentation first. Therefore, I have added the documentation at the top of the readme file for easier accessibility.

fix:add Documentation at the top of readme file

---

bundles/sirix-core/src/main/java/io/sirix/access/trx/node/AbstractDeweyIDManager.java
bundles/sirix-core/src/main/java/io/sirix/access/trx/node/AbstractNodeHashing.java
bundles/sirix-core/src/main/java/io/sirix/access/trx/node/AbstractNodeTrxImpl.java
bundles/sirix-core/src/main/java/io/sirix/access/trx/node/AbstractResourceSession.java
bundles/sirix-core/src/main/java/io/sirix/access/trx/node/PotentialLock.java
bundles/sirix-core/src/main/java/io/sirix/access/trx/node/json/JsonNodeTrxImpl.java
bundles/sirix-core/src/main/java/io/sirix/access/trx/node/xml/XmlNodeReadOnlyTrxImpl.java

Issue: [#440](https://github.com/sirixdb/sirix/issues/440)

fix: fix sonar issues

---

build.gradle

currently the build needs jdk 21, which is not mentioned in the readme and when a wrong jdk is detected a very cryptic error message is thrown (in my case I was running with jdk 20 and the error message was: "2021")
this pr uses the gradle java toolchain support to ensure that jdk 21 is used.
I hope the tests still work, I'm on a mac so I only tried `./gradlew build -x test`

use java toolchain support

---

bundles/sirix-rest-api/src/test/resources/create-sirix-users.sh

Refined `add-user-keycloak.sh` script to include functionality for verifying user existence in Keycloak before proceeding with user addition. This update ensures appropriate messages are displayed based on different scenarios encountered during user checks.

Made changes in order to check if user already exists in keycloak script

---

build.gradle
eclipse/sirix-formatter.xml
gradle/preCommit.gradle
pre-commit

This PR adds a pre-commit hook that formats Java and Kotlin files using Spotless. It includes:
**Pre-commit Hook:** Automatically formats staged code before committing.
No additional setup is required; the hook is created automatically when running build.gradle.

Add pre-commit hook for automatic code formatting

---

bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/AbstractCreateHandler.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/AbstractDeleteHandler.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/AbstractGetHandler.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/AbstractUpdateHandler.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/json/JsonCreate.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/json/JsonDelete.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/json/JsonGet.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/json/JsonUpdate.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/xml/XmlCreate.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/xml/XmlDelete.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/xml/XmlGet.kt
bundles/sirix-rest-api/src/main/kotlin/io/sirix/rest/crud/xml/XmlUpdate.kt

This PR introduces to handle common logic for XML and JSON operations in the CRUD directory. The focus is on enhancing abstraction for create and delete operations, to reduce code duplication and improve maintainability.
1. AbstractCreateHandler Enhancement:
- Extended with implementing Common Method `createDatabaseIfNotExists()`
- Refactored `XMLCreate` and `JsonCreate` to use this shared method.
2. AbstractDeleteHandler Enhancement:
- Extended with implementing Common Method `handle()`
- Refactored `XMLDelete` and `JsonDelete` to use this shared method.
- Review and refine current changes based on feedback
- Extend similar refactoring to other operations.
- Consider creating abstract base classes for classes which have almost similar methods and content.
Please focus on:
1. …

Issue#523: Refactor XML and JSON handling in CRUD operations

---

.gitattributes

This pull request adds a `.gitattributes` file to ensure all `.sh` files maintain LF line endings, preventing Git from converting them to CRLF specifically on Windows systems. This helps ensure consistent execution of shell scripts across different environments.
Especially while running dockers
- Added `.gitattributes` with the rule `*.sh text eol=lf`.
- Applies to all `.sh` files to enforce LF line endings and avoid CRLF conversions.
Shell scripts require LF line endings for proper execution in Unix-based environments. By enforcing LF, this change helps prevent issues related to improper line endings when collaborating on the project across different operating systems.
- Affects only `.sh` files. No other files or default Git settings are modified.
- Ensures consistency and prevents …

Add .gitattributes to enforce LF line endings for .sh files
