sirixdb/sirix

README.md

this will help users who use gradle get setup and ready to go much faster.

Added gradle instructions to readme 

---

README.md

Hi, I am new to GitHub and thought to contribute something. I was going through docs and did some formatting and spelling corrections. Thanks

Corrected some formatting and typos

---

README.md

Fixed some grammar mistakes. Doing the Hacktoberfest 2019 challenge!

Hacktoberfest2019 challenge

---

bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/Auth.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/AuthRole.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/SirixVerticle.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/json/JsonSessionDBStore.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/xml/XmlSessionDBStore.kt

Resolve #124 : Usermanagement for the REST-API (Vert.x / Kotlin / Keycloak)

---

bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/json/JsonCreate.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/json/JsonDelete.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/json/JsonGet.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/json/JsonHead.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/json/JsonUpdate.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/xml/XmlCreate.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/xml/XmlDelete.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/xml/XmlGet.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/xml/XmlHead.kt
bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/xml/XmlUpdate.kt

Change in signatures and variables according to #87

Refactor in rest-api

---

.travis.yml
build.gradle
bundles/sirix-rest-api/build.gradle
bundles/sirix-rest-api/src/test/kotlin/org/sirix/rest/SirixVerticleJsonTest.kt
bundles/sirix-rest-api/src/test/kotlin/org/sirix/rest/SirixVerticleXmlTest.kt
bundles/sirix-rest-api/src/test/resources/create-keycloak-user.sh
bundles/sirix-rest-api/src/test/resources/create-sirix-users.sh
bundles/sirix-rest-api/src/test/resources/docker-compose.yml
bundles/sirix-rest-api/src/test/resources/realm-export.json
libraries.gradle

Automated Rest API Integration test using docker and gradle.
Before test docker-compose will be started and after test docker-compose will be shutdown

Support for automated rest-api integration test - #128

---

README.md
gradle/wrapper/gradle-wrapper.properties

Fixed some grammar errors in README.md, and has been updated Gradle to new version.

Fixed grammar errors, update Gradle

---

bundles/sirix-kotlin-api/src/main/kotlin/org/sirix/axis/CoroutineDescendantAxis.kt
bundles/sirix-kotlin-api/src/test/java/org/sirix/axis/CoroutineDescendantAxisTest.java

DescendantAxis with right page evaluation in coroutine.
I've also added test TestIterationTime - comparision of time in same tree evaluation by DescendantAxis and CoroutineDescendantAxis. You can see that new axis is much slower.

CoroutineDescendantAxis

---

bundles/sirix-core/src/main/java/org/sirix/access/ResourceConfiguration.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/xml/XmlNodeTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/node/NodeKind.java

closes #191 
Following changes were made
- Introduced a parameter in ResouceConfig
- Start respecting the parameter in JsonNodeTrxImpl and XmlNodeTrxImple
- Changes to respect parameter while serializing and deserializing StructNodeDelegate

Closes #191

---

bundles/sirix-core/src/main/java/org/sirix/access/DatabaseType.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractDeweyIDManager.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeFactoryImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/api/json/JsonNodeTrx.java
bundles/sirix-core/src/main/java/org/sirix/index/path/summary/ImmutablePathNode.java
bundles/sirix-core/src/main/java/org/sirix/node/NodeKind.java
bundles/sirix-core/src/main/java/org/sirix/node/NullNode.java
bundles/sirix-core/src/main/java/org/sirix/node/delegates/StructNodeDelegate.java
bundles/sirix-core/src/main/java/org/sirix/node/immutable/json/AbstractImmutableJsonStructuralNode.java
bundles/sirix-core/src/main/java/org/sirix/node/immutable/json/ImmutableObjectStringNode.java
bundles/sirix-core/src/main/java/org/sirix/node/immutable/json/ImmutableStringNode.java
bundles/sirix-core/src/main/java/org/sirix/node/immutable/xml/ImmutableComment.java
bundles/sirix-core/src/main/java/org/sirix/node/immutable/xml/ImmutableElement.java
bundles/sirix-core/src/main/java/org/sirix/node/immutable/xml/ImmutablePI.java
bundles/sirix-core/src/main/java/org/sirix/node/immutable/xml/ImmutableText.java
bundles/sirix-core/src/main/java/org/sirix/node/immutable/xml/ImmutableXmlDocumentRootNode.java
bundles/sirix-core/src/main/java/org/sirix/node/interfaces/StructNode.java
bundles/sirix-core/src/main/java/org/sirix/node/interfaces/immutable/ImmutableStructNode.java
bundles/sirix-core/src/main/java/org/sirix/node/xml/AbstractStructForwardingNode.java
bundles/sirix-core/src/main/java/org/sirix/service/xml/shredder/InsertPosition.java
bundles/sirix-core/src/main/java/org/sirix/settings/Fixed.java

Added lastChild and leftSibling pointer for JsonNodeTrx

---

bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/diff/JsonDiffSerializer.java
bundles/sirix-core/src/main/java/org/sirix/node/SirixDeweyID.java
bundles/sirix-core/src/main/java/org/sirix/node/delegates/StructNodeDelegate.java
bundles/sirix-core/src/main/java/org/sirix/service/json/shredder/JsonShredder.java
bundles/sirix-core/src/test/java/org/sirix/access/node/json/JsonNodeTrxInsertTest.java
bundles/sirix-core/src/test/java/org/sirix/access/node/json/JsonNodeTrxRemoveTest.java
bundles/sirix-core/src/test/resources/json/test.json

Added last child pointer, left sibling pointer in JsonShredder
Added some insert and remove tests

Refactors for last child and left sibling pointer insertions

---

bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonNodeReadOnlyTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/service/xml/shredder/XmlShredder.java
bundles/sirix-core/src/test/java/org/sirix/access/node/json/JsonNodeTrxUpdateTest.java
bundles/sirix-kotlin-cli/src/main/kotlin/org/sirix/cli/commands/Update.kt
bundles/sirix-kotlin-cli/src/main/kotlin/org/sirix/cli/parser/UpdateSubCommand.kt
bundles/sirix-kotlin-cli/src/test/kotlin/org/sirix/cli/commands/CommandTestHelper.kt
bundles/sirix-kotlin-cli/src/test/kotlin/org/sirix/cli/commands/UpdateTest.kt
bundles/sirix-xquery/src/main/java/org/sirix/xquery/json/JsonItemFactory.java
bundles/sirix-xquery/src/main/java/org/sirix/xquery/node/SubtreeBuilder.java

Fix failing test

---

bundles/sirix-xquery/src/test/java/org/sirix/xquery/JsonIntegrationTest.java

Add a test case

---

bundles/sirix-xquery/src/main/java/org/sirix/xquery/function/sdb/SDBFun.java
bundles/sirix-xquery/src/main/java/org/sirix/xquery/function/sdb/trx/SelectParent.java
bundles/sirix-xquery/src/test/java/org/sirix/xquery/function/sdb/trx/SelectParentTest.java

@JohannesLichtenberger please review.

add `sdb:select-parent` xquery function

---

bundles/sirix-core/src/main/java/org/sirix/api/ResourceManager.java

I also fixed a javadoc param error.

removed final keyword from abstract methods params #440

---

.gitignore
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractIndexController.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractResourceManager.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/IndexController.java
bundles/sirix-core/src/main/java/org/sirix/api/visitor/JsonNodeVisitor.java
bundles/sirix-core/src/main/java/org/sirix/node/xml/AbstractStructForwardingNode.java
bundles/sirix-core/src/main/java/org/sirix/page/interfaces/Page.java
bundles/sirix-core/src/main/java/org/sirix/service/xml/xpath/functions/AbstractFunction.java
bundles/sirix-examples/src/main/java/io/sirix/tutorial/xml/XmlDocumentCreator.java

This commit fixes some gradle build warnings. There is still a lot more to do, but this is a decent dent

Fix grale build warnings throughout the codebase

---

README.md

I had a kinda hard time to get the docker compose deployment running. Therefore I provided more detailed steps to ensure an easier first time deployment.

Updated README.md with more detailed docker compose instructions

---

bundles/sirix-core/src/main/java/org/sirix/access/Databases.java
bundles/sirix-core/src/main/java/org/sirix/access/LocalDatabase.java
bundles/sirix-core/src/main/java/org/sirix/access/ResourceConfiguration.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/TransactionImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractIndexController.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractNodeTrxImpl.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/AbstractResourceSession.java
bundles/sirix-core/src/main/java/org/sirix/access/trx/node/json/JsonIndexController.java

Issue: https://github.com/sirixdb/sirix/issues/440

Fix sonar issues

---

bundles/sirix-core/src/main/java/org/sirix/node/SirixDeweyID.java

Wrote a simple javadoc for a function as an example of my writing style. Feel free to give me tips on what is important in a javadoc

doc: add javadoc for parseDivisionValues

---

bundles/sirix-core/src/main/java/org/sirix/node/SirixDeweyID.java

removed hyphens from parseDivisionValues javadoc

doc: remove hyphens

---

bundles/sirix-rest-api/build.gradle

Revert "Bump com.avast.gradle:gradle-docker-compose-plugin from 0.17.6 to 0.17.7"
